package io.github.alelk.pws.domain.model

val TagId.Companion.BeforeGathering get() = parse("before-gathering")
val TagId.Companion.Prayer get() = parse("prayer")
val TagId.Companion.ForBaptism get() = parse("for-baptism")
val TagId.Companion.ForChildrenAndFamilies get() = parse("for-children-and-families")
val TagId.Companion.ForCommunion get() = parse("for-communion")
val TagId.Companion.EndOfGathering get() = parse("end-of-gathering")
val TagId.Companion.AboutTheHolySpirit get() = parse("about-the-holy-spirit")
val TagId.Companion.CallToRepentance get() = parse("call-to-repentance")
val TagId.Companion.CallToWork get() = parse("call-to-work")
val TagId.Companion.ChristianJoy get() = parse("christian-joy")
val TagId.Companion.Christmas get() = parse("christmas")
val TagId.Companion.ComfortForSickAndSuffering get() = parse("comfort-for-sick-and-suffering")
val TagId.Companion.AboutChurch get() = parse("about-church")