package io.github.alelk.pws.android.compose.payment

import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.PreferenceDataStoreFactory
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.emptyPreferences
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

/** In-memory [DataStore]: synchronous and dispatcher-free, so it works under virtual test time. */
internal class FakePreferencesDataStore(initial: Preferences = emptyPreferences()) : DataStore<Preferences> {
  val state = MutableStateFlow(initial)
  var writes = 0
    private set

  override val data: Flow<Preferences> = state

  override suspend fun updateData(transform: suspend (t: Preferences) -> Preferences): Preferences {
    val updated = transform(state.value)
    if (updated != state.value) writes++
    state.value = updated
    return updated
  }
}

/**
 * Copies a golden fork file (`src/testRustore/resources/legacy-entitlement/<name>`, generated by
 * tools/make-legacy-entitlement-fixtures.py) to where the fork kept it, under its real file name.
 */
internal fun legacyPreferencesFile(fixture: String): File {
  val dir = Files.createTempDirectory("legacy-datastore").toFile().apply { deleteOnExit() }
  val target = File(dir, "pws-app-preferences.preferences_pb")
  val bytes = checkNotNull(LegacyEntitlementFixtures::class.java.getResourceAsStream("/legacy-entitlement/$fixture")) {
    "fixture $fixture not found"
  }.use { it.readBytes() }
  target.writeBytes(bytes)
  target.deleteOnExit()
  return target
}

internal fun fileDataStore(file: File): DataStore<Preferences> = PreferenceDataStoreFactory.create(produceFile = { file })

internal fun File.sha256(): String =
  MessageDigest.getInstance("SHA-256").digest(readBytes()).joinToString("") { "%02x".format(it) }

internal object LegacyEntitlementFixtures
